### ISSUE TITLE
Storage put undefined error when passing in file

### ISSUE THREAD

**Issue by Svarto** [nhost/nhost-js-sdk#15]
Hope someone has any ideas on this!

Running a react-native project, just picked the standard [expo-image-picker](https://docs.expo.io/versions/latest/sdk/imagepicker/)  example and took the file uri output and tried to upload it to nhost. Got a weird undefined error:

```

undefined is not an object (evaluating '_nhostJsSdk.storage.put')
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:274:30 in invoke
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:135:28 in invoke
- node_modules/regenerator-runtime/runtime.js:145:19 in PromiseImpl.resolve.then$argument_0
- node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
- node_modules/promise/setimmediate/core.js:123:25 in setImmediate$argument_0
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:146:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:194:17 in _callImmediatesPass
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:458:30 in callImmediates
* [native code]:null in callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:407:6 in __callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:143:6 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:142:17 in __guard$argument_0
* [native code]:null in flushedQueue
* [native code]:null in invokeCallbackAndReturnFlushedQueue
```

this is the full code:
```

import React, { useState, useEffect } from "react";
import { Button, Image, View } from "react-native";
import * as ImagePicker from "expo-image-picker";
import Constants from "expo-constants";
import { storage } from "nhost-js-sdk";

export default function ImagePickerExample() {
  const [image, setImage] = useState(null);

  useEffect(() => {
    (async () => {
      if (Constants.platform.ios) {
        const {
          status,
        } = await ImagePicker.requestCameraRollPermissionsAsync();
        if (status !== "granted") {
          alert("Sorry, we need camera roll permissions to make this work!");
        }
      }
    })();
  }, []);

  const pickImage = async () => {
    let result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.All,
      allowsEditing: true,
      aspect: [4, 3],
      quality: 1,
    });

    if (!result.cancelled) {
      setImage(result.uri);
    }

    // Here I try the nhost-js-sdk storage function:
    try {
      data = await storage.put(
        "/default/test_image.jpg",
        result.uri,
        metadata,
        onUploadProgress
      );
    } catch (e) {
      console.log(result.uri);
      console.log(e);
      // handle error
    }
  };

  return (
    <View style={{ flex: 1, alignItems: "center", justifyContent: "center" }}>
      <Button title="Pick an image from camera roll" onPress={pickImage} />
      {image && (
        <Image source={{ uri: image }} style={{ width: 200, height: 200 }} />
      )}
    </View>
  );
}
```

**Comment by elitan** [comment]
Thanks for this issue. Did you initialize nhost like this: https://github.com/nhost/nhost-js-sdk#setup

We have not done much testing with Nhost on React Native yet. Right now we focus on getting things stabile with Web (React, NextJS, Vue, NuxtJS etc). 

React Native is still a few weeks away, just so you know.

**Comment by Svarto** [comment]
Thanks a lot Johan, I did initialize it as you mentioned however still getting the error. I will for now use the sdk for auth and wait with the storage and try the old "fashioned way" with fetch / axios.

**Comment by elitan** [comment]
OK. then your import is incorrect I think:

`import { storage } from "nhost-js-sdk";`

It should be something like `import { storage } from './nhost.js`

In `./nhost.js` your should initialize your app.

**Comment by Svarto** [comment]
@elitan yes! that was exactly it. Thank you.

Now the request is going through to the server, however I keep getting a 404 Not Found error. I tried with a standard axios post as well and I get the same 404 Not Found error - so something must be off with how I format the upload. But I can't figure out what...

The 404 error message:
```
Error: Not Found
    at /app/dist/routes/index.js:21:26
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at param (/app/node_modules/express/lib/router/index.js:354:14)
    at param (/app/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/app/node_modules/express/lib/router/index.js:410:3)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at /app/node_modules/express/lib/router/index.js:635:15
    at next (/app/node_modules/express/lib/router/index.js:260:14)
    at /app/node_modules/express/lib/router/index.js:635:15
    at next (/app/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)
    at router (/app/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 404,
    payload: { statusCode: 404, error: 'Not Found', message: 'Not Found' },
    headers: {}
  }
}
POST /storage/o/default_images/test_image.jpg 404 60 - 3.116 ms
```

The latest code:
//Nothing changed above or below this:
```
    try {
      data = await storage.put(
        "/default_images/test_image.jpg",
        result.uri,
        null,
        (d) => console.log(d)
      );
    } catch (e) {
      console.log(result.uri);
      console.log(e);
    }
  };
```

My HBP table: [IMGUR LINK](https://imgur.com/a/m9cwmzC)

**Comment by elitan** [comment]
OK. good. Now the issue is probably with your storage rules. How does your `rules.yaml` file look like in `./custom/storage-rules/rules.yaml`? Or are you using Nhost for your backend?

**Comment by elitan** [comment]
Just a note: The storage is completely decoupled from the data/api. If you want to save information about files in the database, you need to do that insertion after the file has been uploaded.

**Comment by Svarto** [comment]
Currently I am trying out HBP on my home LAN, so using the docker-compose.yml. Ok that is good to know about the database/api and the s3 storage.

My storage_rules:

**Comment by elitan** [comment]
You are right. What you can do as a starter is to apply the following rules.yaml:

```yaml
functions:
  isAuthenticated: 'return !!request.auth'
  isOwner: "return !!request.auth && userId === request.auth['user-id']"
  validToken: 'return request.query.token === resource.Metadata.token'
  public: 'return true' 
paths:
  /public*:
    read: 'public()'
    write: 'public()'
  /user/:userId/:
    list: 'isOwner(userId)'
  /user/:userId/:fileId:
    read: 'isOwner(userId) || validToken()'
    write: 'isOwner(userId)'
```

Then make sure to restart HBP.

Then upload a file to `/public/test_image.jpg`.

Unfortunately we don't have much documentation about this yet (https://nhost.github.io/hasura-backend-plus/configuration.html#storage-rules)

**Comment by Svarto** [comment]
Got it to work, here is the code that works in react-native. Had to pass in a slightly different format for the file, than what is done on the web. Using the documentation sample code of imagepicker, and combining it with the nhost-js-sdk to upload a image to 
```

import React, { useState, useEffect } from "react";
import { Button, Image, View, Text } from "react-native";
import * as ImagePicker from "expo-image-picker";
import Constants from "expo-constants";
import { storage, auth } from "../services/nhost_sdk";

export default function ImagePickerExample() {
  const [image, setImage] = useState(null);

  useEffect(() => {
    (async () => {
      if (Constants.platform.ios) {
        const {
          status,
        } = await ImagePicker.requestCameraRollPermissionsAsync();
        if (status !== "granted") {
          alert("Sorry, we need camera roll permissions to make this work!");
        }
      }
    })();
  }, []);

  const pickImage = async () => {
    let result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.All,
      allowsEditing: true,
      quality: 1,
      base64: true,
    });

    if (!result.cancelled) {
      setImage(result.uri);
    }
    // nhost-js-sdk code uploading a file called default_avatar.png to /public/default_avatar.png
    try {
      let data = await storage.put(
        "/public/default_avatar.png",
        { uri: result.uri, name: "default_avatar.png", type: "image/png" },
        null,
        (d) => console.log(d)
      );
      console.log(data);
    } catch (e) {
      console.log(e);
    }
  };

  const requestMetadata = async () => {
    let metadata = await storage.getMetadata("/public/");
    console.log(metadata);
  };

  return (
    <View
      style={{ flex: 1, alignItems: "center", justifyContent: "space-around" }}
    >
      <Button title="Pick an image from camera roll" onPress={pickImage} />
      {image && (
        <Image source={{ uri: image }} style={{ width: 200, height: 200 }} />
      )}
      <Button title="Get the metadata folder!" onPress={requestMetadata} />
      <Text>This is the picture from my server</Text>
      <Image
        source={{
          uri:
            "https://minio.svarto-server.com/storage/o/public/test_image3.jpg?token=886e1e69-34ec-464a-a4bd-58334e8ce5bd",
        }}
        style={{ width: 200, height: 200 }}
      />
    </View>
  );
}

```
